### ISSUE TITLE
Release as 0.5.0(-pre)?

### ISSUE THREAD

**Issue by Yuki-Inoue** [linjunpop/capistrano-logrotate#11]
Hi, first, thank you for merging my PR (#9).

If possible, could you released the current master as 0.5.0 (or, as [prelease version](https://guides.rubygems.org/patterns/#prerelease-gems), e.g. '0.5.0-pre')?
Unless released to rubygems.org, I need to specify this gem as `gihtub` dependency, which I think is not so good operation...

**Comment by linjunpop** [comment]
Ok, will publish a new version.

**Comment by linjunpop** [comment]
Published v0.5.0
