### ISSUE TITLE
Upload the conf to tmp folder, not shared folder?

### ISSUE THREAD

**Issue by Yuki-Inoue** [linjunpop/capistrano-logrotate#8]
Currently, if I'm not mistaken, this gem operates by

1. first uploading conf file to `${app_path}/shared/logrotate_conf`
2. move it to `:logrotate_conf_path` with `mv` command

Actually, this does not work properly if the login user used in uploading the conf file is different from the user which is used on the normal deployment;  I do so because I'd like to refrain from using the `sudo` capability on the daily operation.

In short, in my config, "the owner user of shared folder" != "the user who can sudo".

So, I thought it would be good if we upload the logrotate_conf file to `tmp` folder (the folder specified by `:tmp_dir`), not to the shared folder.

As seen from the doc, I think it is common for Capistrano to use tmp folder for temporal file uploads:
https://capistranorb.com/documentation/getting-started/configuration/  (search for `tmp_dir`)

Any opinion?  If this fix sounds sensible, I can create PR.

**Comment by linjunpop** [comment]
Make sense, PR appreciated!
